version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: api-mvc-backend-pets_db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      